export const userConst = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_REQUEST',
    REGISTER_FAIL: 'USERS_REGISTER_FAIL',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAIL: 'USERS_LOGIN_FAIL',

    LOGOUT: 'USERS_LOGOUT',

    GETUSER_REQUEST: 'USERS_GETUSER_REQUEST',
    GETUSER_SUCCESS: 'USERS_GETUSER_SUCCESS',
    GETUSER_FAIL: 'USERS_GETUSER_FAIL'

};
