export const dogConst = {
    
    ADDDOG_REQUEST: 'DOG_ADDDOG_REQUEST',
    ADDDOG_SUCCESS: 'DOG_ADDDOG_SUCCESS',
    ADDDOG_FAIL: 'DOG_ADDDOG_FAIL',

    LOGOUT: 'USERS_LOGOUT',

    GETDOG_REQUEST: 'DOG_GETDOG_REQUEST',
    GETDOG_SUCCESS: 'DOG_GETDOG_SUCCESS',
    GETDOG_FAIL: 'DOG_GETDOG_FAIL'

};
